# Generated by Django 4.1.4 on 2023-01-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transction",
            new_name="Transaction",
        ),
    ]
