# Generated by Django 4.1.4 on 2023-02-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
        ("transactions", "0003_remove_transaction_hour_transaction_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stores.store"
            ),
        ),
    ]
